In [29]:
def compute():
    try:
        5/0
    except ZeroDivisionError:
        print('Divide by zero exception occured')
    except:
        print('Other exception occured')
    finally:
        print('finally called')

compute()


Divide by zero exception occured
finally called


In [30]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for s in range(len(subjects)):
    for v in range(len(verbs)):
        for o in range(len(objects)):
            print(subjects[s] + ' ' + verbs[v] + ' ' + objects[o])

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [27]:
import numpy as np

def AlexandreTheophileVandermonde(ipvector, size, decr):
    
    if type(ipvector) != list:
        print('First Parameter must be a list')
        return;
    if type(size) != int:
        print('Second Parameter must be an integer')
        return;
    if type(decr) != bool:
        print('Third Parameter must be a boolean')
        return;
    
    vecsize = len(ipvector)
    ipvector = np.asarray(ipvector).reshape(vecsize, 1)

    ary = np.ones([ipvector.size, n], dtype = int)
    ary = ipvector * ary;

    p = 0
    if(decr == True):
        p = n - 1
    for j in range(ary.shape[1]):    
        for i in range(ary.shape[0]):
            ary[i, j] = ary[i, j] ** p
        if(decr == True):
            p = p - 1
        else:      
            p = p + 1

    print(ary)


    
    # ary = np.array()
    # print(ary)
    # for x in ipvector:
    #    for i in range(n):
    #        print(x**i)
    #        print(' ')
    # print('\r\n')

arry = [1,2,3,4,5]
n = 6
print('Increasing matrix')
AlexandreTheophileVandermonde(arry, n, True)
print('\nDecreasing matrix')
AlexandreTheophileVandermonde(arry, n, False)

Increasing matrix
[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]]

Decreasing matrix
[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]]
